# Pinterest link url
PINTEREST_URL = "https://api.pinterest.com/v1/"

# Pinterest api links
BOARD = "boards/"
FOLLOW = "following/"
FOLLOWER = "followers/"
INTEREST = "interests/"
LIKE = "likes/"
ME = "me/"
PIN = "pins/"
SEARCH = "search/"
SUGGEST = "suggested/"
USER = "users/"

# data entry field
BOARD_DATA = "board"
CURSOR = "cursor"
FIELDS = "fields"
IMAGE64 = "image_base64"
IMAGE_URL = "image_url"
PINID = "pin"
QUERY = "query"
TOKEN = "access_token"
USER_DATA = "user"

# field parameter
ACC_TYPE = "account_type"
ATTRIBUTION="attribution"
BIO = "bio"
COLOR = "color"
COUNT = "counts"
CREATED = "created_at"
CREATOR = "creator"
DESCRIPTION = "description"
FIRST = "first_name"
ID = "id"
IMAGE = "image"
LAST = "last_name"
LINK = "link"
MEDIA = "media"
METADATA="metadata"
NAME = "name"
NOTE = "note"
URL = "url"
USERNAME = "username"
